#!/usr/bin/env bash

set -eu

OUT_NOISY_WARNINGS=noisy_warnings_fasm.log

source "$(dirname "$(realpath "$0")")/vpr_common"
parse_args "$@"

TOP="${EBLIF%.*}"
FASM_EXTRA=${TOP}_fasm_extra.fasm

run_genfasm

if [[ -f $FASM_EXTRA ]]; then
	echo "writing final fasm"
	cat "${TOP}.fasm" "$FASM_EXTRA" > tmp.fasm
	mv tmp.fasm "${TOP}.fasm"
fi

mv vpr_stdout.log fasm.log
